name: Triggers Just Once

on:
  pull_request:
    types: [edited]
    branches:
    - master
  pull_request_review:
    branches:
    - master

jobs:
  TriggerOnce:
    runs-on: ubuntu-latest
    steps:
      
      - name: Echo a line
        run: |
              echo 'hello'
