name: CheckWhenTriggered

on:
  workflow_run:
      workflows: ["validateTitle"]
      types: [completed]
  #pull_request:
  #  types: [opened, edited, reopened, synchronize]
  #  branches:
  #  - master
  #push:
  #  branches:
  #  - master

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      
      - name: Echo for not draft
        run: |
              echo 'success'
              
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      
      - name: Echo for not draft
        run: |
              echo 'failureeeee'
