name: CheckDraft

on:
  pull_request:
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  
jobs:
  Check-Draft:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Echo for not draft
        if: github.event.pull_request.draft == false
        run: |
              echo 'not draft'
              
      - name: Echo for draft
        if: github.event.pull_request.draft == true
        run: |
               echo 'draft'
              
      - name: Echo for draft
        run: |
              echo 'all cases'       
              
              
