name: CI
 
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master 
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_WORKFLOW_ID: ${{github.run_id}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Extract branch name
          run: echo "PR_Branch_Name=${{ github.head_ref }}" >> $GITHUB_ENV  

        - name: Validate PR Title
          id: validatePRTitle
          run:  |
                  echo PR Numer is: $GITHUB_PR_NUMBER

                  restApiPRTitle=$(curl \
                                        -H "Accept: application/vnd.github.v3+json" \
                                        https://api.github.com/repos/naregkar/repo1/pulls/$GITHUB_PR_NUMBER | jq  -r '.title')

                  echo $restApiPRTitle

                  if [[ $restApiPRTitle =~ ^\[DT-[0-9]+\] ]]; then
                    #if the title matches the pattern
                    echo 'PR Title is in correct format.'

                    jira_IdUnparsed=$restApiPRTitle
                    echo $jira_IdUnparsed
                    JiraId=${jira_IdUnparsed%]*}
                    JiraId=${JiraId:1}
                    
                    echo $JiraId
                    echo 'after jira id'
                    
                    restApiGET=$(curl --request GET \
                    --url 'https://naregkar.atlassian.net/rest/api/3/issue/${JiraId}/' \
                    --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                    --header 'Accept: application/json' | jq -r '.fields.fixVersions[].name');       
                    
                    echo 'after curl'
                    
                    issue_fix_version=$restApiGET
                    echo 'issue_fix_version: ' $issue_fix_version
                    
                    git config --global user.name "naregkar"
                    git config --global user.email "naregkar@gmail.com"

                    git fetch
                    git checkout "${{ env.PR_Branch_Name }}"

                    cd .github
                    > version

                    echo 'issue version:' $issue_fix_version

                    echo $issue_fix_version >> version
                    cat version

                    git add version
                    git diff-index --quiet HEAD || git commit -m 'Updating the file version from Jira Issue'
                    git push
                    
                    cd .github
                    line=$(head -n 1 version)
                    echo $line
                    echo "pr_version=$(echo $line)" >> $GITHUB_ENV
                    
                    contentMaster=$(curl \
                                 -H "Accept: application/vnd.github.v3+json" \
                                 https://api.github.com/repos/naregkar/repo1/contents/.github/version | jq -r '.content')

                    master_version=$(echo $contentMaster | base64 -d)
                    
                    echo 'pr version is:' $pr_version
                    echo 'master version is:' $master_version

                    if [[ "$pr_version" == "$master_version" ]]; then
                      echo 'Matching PR and master versions.'
                    else
                      echo 'PR branch planned for a future release. Cannot merge.'
                      exit 1
                    fi


                  else
                    echo 'PR Title does not comply with the required pattern.'                  
                    exit 1
                  fi
