name: Triggers Once

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  TriggerOnce:
    runs-on: ubuntu-latest
    steps:
      
      - name: Echo a line
        run: |
              echo 'hello'
